### PR TITLE
Support of MorphOS (Amiga compatible).

### PR DESCRIPTION
**Pull request by polluks**
lhasa is coming home :-)

### CODE REVIEW

**Comment by fragglet** [comment]
lha_arch_unix.c seems like the wrong place to put Amiga-specific code.

**Comment by fragglet** [comment]
Also, see the TODO comment above the function you've changed. If using the UNIX arch code is the easiest way to make this compile on Amiga, it would be better to come up with a solution that is not tied to a single OS.

**Comment by polluks** [comment]
I read your TODO comment, in my opinion you already wrote the solution in lha_arch_win32.c. Do you prefer something like "lha_arch_amiga.c"?

**Comment by fragglet** [comment]
Preferred solution is an autotools-based #define that checks for vasprintf in libc (ie. HAS_VASPRINTF ...)  and uses a fallback if it doesn't exist.

I'd prefer to avoid adding lha_arch_amiga.c unless it's really necessary and it seems like we can probably avoid it.

**Comment by polluks** [comment]
I see. So you are waiting for official autotools support?
Not http://www.jhweiss.de/software/snprintf.html

**Comment by polluks** [comment]
I have found a solution: Linking with Libiberty :-)
https://en.wikipedia.org/wiki/Libiberty
Here is my port
http://aminet.net/package/util/arc/lhasa
Maybe you can add the library to autoconf.

**Pull request closed without merging**
